"""initial_schema_10_tables

Revision ID: 6d290aba8a80
Revises: 
Create Date: 2026-02-06 17:59:22.869342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d290aba8a80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.String(length=100), nullable=False, comment="e.g., 'llm-proxy'"),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Semantic version'),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of capabilities'),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema'),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft | review | published | deprecated | retired'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_index('idx_agent_published', 'agent', ['published_at'], unique=False)
    op.create_index('idx_agent_status', 'agent', ['status'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='OIDC sub claim'),
    sa.Column('provider', sa.String(length=255), nullable=False, comment='OIDC iss claim'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_app_user_provider_external_id')
    )
    op.create_index('idx_app_user_active', 'app_user', ['is_active'], unique=False)
    op.create_index('idx_app_user_email', 'app_user', ['email'], unique=False)
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='namespace.action'),
    sa.Column('actor_type', sa.String(length=50), nullable=False, comment='user | agent | system'),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('action_verb', sa.String(length=50), nullable=False, comment='created | updated | deleted | ...'),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='session_id, request_id, trace_id'),
    sa.Column('result_status', sa.String(length=50), nullable=False, comment='success | failure'),
    sa.Column('result_error', sa.Text(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_event', ['actor_type', 'actor_id'], unique=False)
    op.create_index('idx_audit_context', 'audit_event', ['context'], unique=False, postgresql_using='gin')
    op.create_index('idx_audit_event_type', 'audit_event', ['event_type'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_event', ['timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.create_table('instruction',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Semantic version'),
    sa.Column('template', sa.Text(), nullable=False, comment='Template with placeholders'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of parameter names'),
    sa.Column('applicable_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of agent IDs'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft | review | published | deprecated | retired'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_index('idx_instruction_status', 'instruction', ['status'], unique=False)
    op.create_table('job_type',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Semantic version'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema'),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft | review | published | deprecated | retired'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_index('idx_job_type_status', 'job_type', ['status'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='active | paused | archived'),
    sa.Column('llm_id', sa.String(length=100), nullable=False, comment='LLM model identifier'),
    sa.Column('llm_version', sa.String(length=50), nullable=False, comment='Locked at creation for reproducibility'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_created', 'session', ['created_at'], unique=False)
    op.create_index('idx_session_owner', 'session', ['owner_user_id'], unique=False)
    op.create_index('idx_session_status', 'session', ['status'], unique=False)
    op.create_table('meta_proposal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('original_request', sa.Text(), nullable=False, comment="User's meta: request"),
    sa.Column('scope', sa.String(length=50), nullable=False, comment='workflow | catalog | parameters'),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of proposed changes'),
    sa.Column('unchanged', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of things that stay same'),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of risk objects'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending | user_confirmed | sandbox_running | sandbox_passed | sandbox_failed | production_deployed | rejected'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meta_proposal_session', 'meta_proposal', ['session_id'], unique=False)
    op.create_index('idx_meta_proposal_status', 'meta_proposal', ['status'], unique=False)
    op.create_index('idx_meta_proposal_user', 'meta_proposal', ['created_by_user_id'], unique=False)
    op.create_table('subsession',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_session_id', sa.UUID(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False, comment='From catalog'),
    sa.Column('agent_version', sa.String(length=50), nullable=False, comment='Semantic version'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='running | completed | failed'),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Read-only input data snapshot'),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured output'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subsession_agent', 'subsession', ['agent_id', 'agent_version'], unique=False)
    op.create_index('idx_subsession_parent', 'subsession', ['parent_session_id'], unique=False)
    op.create_index('idx_subsession_status', 'subsession', ['status'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False, comment='From catalog'),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('subsession_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='PENDING | SCHEDULED | RUNNING | COMPLETED | FAILED'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsession_id'], ['subsession.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_created', 'job', ['created_at'], unique=False)
    op.create_index('idx_job_session', 'job', ['session_id'], unique=False)
    op.create_index('idx_job_status', 'job', ['status'], unique=False)
    op.create_index('idx_job_type', 'job', ['job_type'], unique=False)
    op.create_table('sandbox_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('checklist_version', sa.String(length=50), nullable=False),
    sa.Column('execution_status', sa.String(length=50), nullable=False, comment='success | failure'),
    sa.Column('checklist_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of check results'),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('promotion_decision', sa.String(length=50), nullable=False, comment='approve | reject | iterate'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['meta_proposal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sandbox_run_proposal', 'sandbox_run', ['proposal_id'], unique=False)
    op.create_index('idx_sandbox_run_status', 'sandbox_run', ['execution_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sandbox_run_status', table_name='sandbox_run')
    op.drop_index('idx_sandbox_run_proposal', table_name='sandbox_run')
    op.drop_table('sandbox_run')
    op.drop_index('idx_job_type', table_name='job')
    op.drop_index('idx_job_status', table_name='job')
    op.drop_index('idx_job_session', table_name='job')
    op.drop_index('idx_job_created', table_name='job')
    op.drop_table('job')
    op.drop_index('idx_subsession_status', table_name='subsession')
    op.drop_index('idx_subsession_parent', table_name='subsession')
    op.drop_index('idx_subsession_agent', table_name='subsession')
    op.drop_table('subsession')
    op.drop_index('idx_meta_proposal_user', table_name='meta_proposal')
    op.drop_index('idx_meta_proposal_status', table_name='meta_proposal')
    op.drop_index('idx_meta_proposal_session', table_name='meta_proposal')
    op.drop_table('meta_proposal')
    op.drop_index('idx_session_status', table_name='session')
    op.drop_index('idx_session_owner', table_name='session')
    op.drop_index('idx_session_created', table_name='session')
    op.drop_table('session')
    op.drop_index('idx_job_type_status', table_name='job_type')
    op.drop_table('job_type')
    op.drop_index('idx_instruction_status', table_name='instruction')
    op.drop_table('instruction')
    op.drop_index('idx_audit_timestamp', table_name='audit_event', postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_audit_event_type', table_name='audit_event')
    op.drop_index('idx_audit_context', table_name='audit_event', postgresql_using='gin')
    op.drop_index('idx_audit_actor', table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index('idx_app_user_email', table_name='app_user')
    op.drop_index('idx_app_user_active', table_name='app_user')
    op.drop_table('app_user')
    op.drop_index('idx_agent_status', table_name='agent')
    op.drop_index('idx_agent_published', table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###
